### ISSUE TITLE
Parameter confusion

### ISSUE THREAD

**Issue by Joseph94m** [NTSC-Community/MatchZoo#276]
Hey,

I am having trouble understanding some configuration parameters for training even after I read the documentation.
For the sake of explanation, let's take an example.
I have a relation_train with 800 million entries.
I would like to set the following configuration parameters so that my network actually uses the data properly:
(Of course I am using user_iter=true because otherwise I can't fit it all in memory)
{
       "num_iters": 400,
      "display_interval": 10,
        "query_per_iter": 50,
        "batch_per_iter": 5,
        "batch_size": 100,
}
With these parameters, I am not even able to get out of the first iteration: (it is taking tooo long, I have 50 GB of memory and  tesla K80)
[Model] Model Compile Done.
[08-09-2018 09:53:27]   [Train:train] Iter:0    loss=1.000167

Are my configuration parameters wrong? What should I increase/decrease? Can someone explain how these parameters interaction with each other?

Thanks a lot

**Comment by pl8787** [comment]
Try to set `"display_interval": 1,` and see what happen.

**Comment by Joseph94m** [comment]
Hello,

Thanks for the response. That did reduce the training time considerably.
Let's say that I have 100k queries, and if I am running 50 queries per iteration with 400 iterations. This means that at most i will train over 50x400= 20,000 queries. But if I crease the number of queries per iteration, I run out of memory. Do you recommend instead that I increase the number of iterations from 400 to ... 4000?

**Comment by ZeonTrevor** [comment]
@Joseph94m 

1. > Can someone explain how these parameters interaction with each other? 

   So in the first case, changing "display_interval" from 10 to 1, reduces the training time considerably because the number of training pairs per iteration reduces from 1000 to 100 respectively. I have made the calculation as follows for each iteration: 
   - ```display_interval``` = 'steps_per_epoch' (Keras) and it indicates the number of batches to fetch for one iteration.
   - ```query_per_iter```: setting it to 50 essentially means that each batch of training instances in this iteration is sampled from the pairs that are generated from 50 randomly selected queries https://github.com/faneshion/MatchZoo/blob/5bd90d999fd47558be3154eb5bbc3dcd41a834b3/matchzoo/inputs/pair_generator.py#L63-L73
   - ```batch_per_iter```: this is essentially linked to ```display_interval```. 
If ```batch_per_iter``` = 5, ```display_interval``` = 10 &rarr; then first 5 batches in the iteration will be sampled from the pairs generated from 50 randomly selected queries and the next 5 will be sampled from those generated from a new set of 50 randomly selected queries 
https://github.com/faneshion/MatchZoo/blob/5bd90d999fd47558be3154eb5bbc3dcd41a834b3/matchzoo/inputs/pair_generator.py#L139-L142

2. > But if I increase the number of queries per iteration, I run out of memory.

   For your follow-up question, I think the issue of running out of memory is clearly related to #273 because increasing the number of queries per iteration would lead to more pairs generated each time ```query_per_item``` number of queries are randomly sampled. And these pairs keep getting appended to the ```pair_list``` as you have highlighted in #273
